
all:\
  make_lib\
  make_common\
  make_speedy\
  make_prepbufr\
  make_thinning

make_lib:
	$(MAKE) -C lib

make_common:
	$(MAKE) -C common

make_speedy:
	$(MAKE) -C speedy

make_prepbufr:
	$(MAKE) -C prepbufr

make_thinning:
	$(MAKE) -C thinning



clean:\
  clean_lib\
  clean_common\
  clean_speedy\
  clean_prepbufr\
  clean_thinning

clean_lib:
	$(MAKE) -C lib clean

clean_common:
	$(MAKE) -C common clean

clean_speedy:
	$(MAKE) -C speedy clean

clean_prepbufr:
	$(MAKE) -C prepbufr clean

clean_thinning:
	$(MAKE) -C thinning clean

